swipe:
  3:
    left:
      command: ''
    right:
      command: ''
    up:
      command: 'xdotool key ctrl+F9'
    down:
      command: 'xdotool key ctrl+F9'
  4:
    left:
      command: 'xdotool key ctrl+alt+Right'
    right:
      command: 'xdotool key ctrl+alt+Left'
    up:
      command: 'xdotool key ctrl+F8'
    down:
      command: 'xdotool key ctrl+F8'
pinch:
  2:
    in:
      command: ''
    out:
      command: ''

threshold:
  swipe: 1.5
  pinch: 0

interval:
  swipe: 1
  pinch: 1.2
