swipe:
  3:
    left:
      command: ''
    right:
      command: ''
    up:
      command: 'xdotool key super+s'
    down:
      command: 'xdotool key super+s'
  4:
    left:
      command: ''
    right:
      command: ''
    up:
      command: 'xdotool key ctrl+alt+Down'
    down:
      command: 'xdotool key ctrl+alt+Up'
pinch:
  2:
    in:
      command: ''
    out:
      command: ''

threshold:
  swipe: 1.5
  pinch: 0

interval:
  swipe: 1
  pinch: 1.2
